env:
  es6: true
  node: true
extends: 'eslint:recommended'
rules:
  indent:
    - error
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  no-console:
    - warn
    - allow:
      - warn
      - error
      - info
